#!/bin/sh
# System init script
/bin/mount -t proc proc /proc
/bin/mount -t sysfs sysfs /sys
/bin/mount -t devtmpfs devtmpfs /dev 2>/dev/null || true
/sbin/sysctl -w kernel.printk='0 0 0 0' 2>/dev/null || true

# Set hostname
hostname ailab

# Create /dev/null if not present
[ -c /dev/null ] || mknod /dev/null c 1 3

# Ready!
echo 'System ready.'
